In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [27]:
feature = pd.read_csv('data/feature.csv', index_col=0)
price = pd.read_csv('data/price.csv', index_col=0)

In [28]:
df = pd.concat([feature, price], axis=1)

In [29]:
df.corr()

,area,bathroom,bedroom,lat,long,school,mrt,age,type_condo,type_hdb,bathroom_area,bedroom_area,remaining_area,convenience,distance_from_central,price_sqft
area,1.000000,0.701606,0.761255,0.075706,-0.047342,0.013446,-0.112479,0.143876,-0.079657,0.079657,0.892489,0.930523,0.703908,-0.037418,0.112125,-0.189699
bathroom,0.701606,1.000000,0.656029,0.080099,0.000237,-0.005949,-0.131680,-0.003853,0.109343,-0.109343,0.911181,0.703371,0.249378,-0.064874,0.103933,-0.063693
bedroom,0.761255,0.656029,1.000000,0.276940,0.011400,0.209758,-0.220877,0.219340,-0.333543,0.333543,0.705989,0.912727,0.179164,0.104603,0.288050,-0.422425
lat,0.075706,0.080099,0.276940,1.000000,0.076324,0.565930,-0.342833,-0.024168,-0.336320,0.336320,0.037311,0.169406,-0.095221,0.395805,0.758342,-0.583385
long,-0.047342,0.000237,0.011400,0.076324,1.000000,0.108215,-0.081939,-0.064216,0.011981,-0.011981,-0.029219,-0.023170,-0.075566,0.068332,0.250361,-0.069531
school,0.013446,-0.005949,0.209758,0.565930,0.108215,1.000000,-0.166031,0.060975,-0.369423,0.369423,-0.042618,0.092344,-0.093377,0.896743,0.417048,-0.442197
mrt,-0.112479,-0.131680,-0.220877,-0.342833,-0.081939,-0.166031,1.000000,-0.116762,0.181266,-0.181266,-0.107546,-0.164558,0.025010,0.287523,-0.372251,0.403920
age,0.143876,-0.003853,0.219340,-0.024168,-0.064216,0.060975,-0.116762,1.000000,-0.599195,0.599195,0.039182,0.171830,0.087904,0.006821,0.004781,-0.580174
type_condo,-0.079657,0.109343,-0.333543,-0.336320,0.011981,-0.369423,0.181266,-0.599195,1.000000,-1.000000,0.085622,-0.186497,0.043873,-0.277455,-0.286171,0.795512
type_hdb,0.079657,-0.109343,0.333543,0.336320,-0.011981,0.369423,-0.181266,0.599195,-1.000000,1.000000,-0.085622,0.186497,-0.043873,0.277455,0.286171,-0.795512
bathroom_area,0.892489,0.911181,0.705989,0.037311,-0.029219,-0.042618,-0.107546,0.039182,0.085622,-0.085622,1.000000,0.865226,0.455888,-0.089657,0.068408,-0.060933
bedroom_area,0.930523,0.703371,0.912727,0.169406,-0.023170,0.092344,-0.164558,0.171830,-0.186497,0.186497,0.865226,1.000000,0.411184,0.015839,0.197546,-0.284501
remaining_area,0.703908,0.249378,0.179164,-0.095221,-0.075566,-0.093377,0.025010,0.087904,0.043873,-0.043873,0.455888,0.411184,1.000000,-0.079469,-0.059182,-0.013792
convenience,-0.037418,-0.064874,0.104603,0.395805,0.068332,0.896743,0.287523,0.006821,-0.277455,0.277455,-0.089657,0.015839,-0.079469,1.000000,0.238000,-0.248214
distance_from_central,0.112125,0.103933,0.288050,0.758342,0.250361,0.417048,-0.372251,0.004781,-0.286171,0.286171,0.068408,0.197546,-0.059182,0.238000,1.000000,-0.594231
price_sqft,-0.189699,-0.063693,-0.422425,-0.583385,-0.069531,-0.442197,0.403920,-0.580174,0.795512,-0.795512,-0.060933,-0.284501,-0.013792,-0.248214,-0.594231,1.000000

In [30]:
hdb = df[df['type_hdb']==1]
condo = df[df['type_condo'] ==1]

In [31]:
hdb.corr()

,area,bathroom,bedroom,lat,long,school,mrt,age,type_condo,type_hdb,bathroom_area,bedroom_area,remaining_area,convenience,distance_from_central,price_sqft
area,1.000000,0.507032,0.774651,0.189404,-0.037130,0.060652,-0.086167,-0.156708,NaN,NaN,0.885533,0.938093,0.731049,0.031697,0.290914,-0.099008
bathroom,0.507032,1.000000,0.417357,0.202092,-0.018496,0.051040,-0.084252,-0.179731,NaN,NaN,0.819369,0.487346,0.184125,0.023110,0.227786,-0.040369
bedroom,0.774651,0.417357,1.000000,0.188586,-0.007285,0.083015,-0.055497,-0.209070,NaN,NaN,0.687717,0.921102,0.211215,0.062338,0.256456,-0.031828
lat,0.189404,0.202092,0.188586,1.000000,0.055104,0.447339,-0.145232,-0.550086,NaN,NaN,0.198562,0.186994,0.107731,0.382614,0.676833,-0.315759
long,-0.037130,-0.018496,-0.007285,0.055104,1.000000,0.218064,0.027377,-0.069755,NaN,NaN,-0.040714,-0.035032,-0.023283,0.216315,0.118233,0.157366
school,0.060652,0.051040,0.083015,0.447339,0.218064,1.000000,-0.003473,-0.331266,NaN,NaN,0.042154,0.055577,0.051902,0.952811,0.374451,-0.114098
mrt,-0.086167,-0.084252,-0.055497,-0.145232,0.027377,-0.003473,1.000000,0.146418,NaN,NaN,-0.087972,-0.072504,-0.072967,0.300253,-0.184313,0.204065
age,-0.156708,-0.179731,-0.209070,-0.550086,-0.069755,-0.331266,0.146418,1.000000,NaN,NaN,-0.140402,-0.151509,-0.105627,-0.271536,-0.476811,-0.264921
type_condo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
type_hdb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bathroom_area,0.885533,0.819369,0.687717,0.198562,-0.040714,0.042154,-0.087972,-0.140402,NaN,NaN,1.000000,0.845523,0.524100,0.013504,0.270544,-0.086249
bedroom_area,0.938093,0.487346,0.921102,0.186994,-0.035032,0.055577,-0.072504,-0.151509,NaN,NaN,0.845523,1.000000,0.460512,0.031003,0.279802,-0.080810
remaining_area,0.731049,0.184125,0.211215,0.107731,-0.023283,0.051902,-0.072967,-0.105627,NaN,NaN,0.524100,0.460512,1.000000,0.027357,0.194331,-0.095012
convenience,0.031697,0.023110,0.062338,0.382614,0.216315,0.952811,0.300253,-0.271536,NaN,NaN,0.013504,0.031003,0.027357,1.000000,0.301224,-0.046887
distance_from_central,0.290914,0.227786,0.256456,0.676833,0.118233,0.374451,-0.184313,-0.476811,NaN,NaN,0.270544,0.279802,0.194331,0.301224,1.000000,-0.365757
price_sqft,-0.099008,-0.040369,-0.031828,-0.315759,0.157366,-0.114098,0.204065,-0.264921,NaN,NaN,-0.086249,-0.080810,-0.095012,-0.046887,-0.365757,1.000000

In [32]:
condo.corr()

,area,bathroom,bedroom,lat,long,school,mrt,age,type_condo,type_hdb,bathroom_area,bedroom_area,remaining_area,convenience,distance_from_central,price_sqft
area,1.000000,0.776055,0.784259,-0.010719,-0.053404,-0.061370,-0.104359,0.361636,NaN,NaN,0.919834,0.935150,0.703618,-0.115208,0.016401,-0.236302
bathroom,0.776055,1.000000,0.820065,0.109375,0.004977,0.036548,-0.169445,0.233856,NaN,NaN,0.926172,0.825100,0.263048,-0.060816,0.124686,-0.268653
bedroom,0.784259,0.820065,1.000000,0.187234,0.029540,0.111857,-0.207051,0.213371,NaN,NaN,0.811685,0.919278,0.204014,-0.012023,0.197414,-0.317825
lat,-0.010719,0.109375,0.187234,1.000000,0.107958,0.551425,-0.376254,-0.052724,NaN,NaN,0.030857,0.079301,-0.173097,0.300881,0.767263,-0.674457
long,-0.053404,0.004977,0.029540,0.107958,1.000000,0.035836,-0.143314,-0.076095,NaN,NaN,-0.028936,-0.013549,-0.107154,-0.046871,0.361373,-0.203385
school,-0.061370,0.036548,0.111857,0.551425,0.035836,1.000000,-0.165593,-0.073669,NaN,NaN,-0.034824,0.007953,-0.159461,0.834418,0.342337,-0.350656
mrt,-0.104359,-0.169445,-0.207051,-0.376254,-0.143314,-0.165593,1.000000,-0.119734,NaN,NaN,-0.133926,-0.156903,0.042948,0.405349,-0.395673,0.477437
age,0.361636,0.233856,0.213371,-0.052724,-0.076095,-0.073669,-0.119734,1.000000,NaN,NaN,0.290044,0.288315,0.358637,-0.135201,-0.007425,-0.308243
type_condo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
type_hdb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bathroom_area,0.919834,0.926172,0.811685,0.030857,-0.028936,-0.034824,-0.133926,0.290044,NaN,NaN,1.000000,0.932911,0.440977,-0.107125,0.050286,-0.229385
bedroom_area,0.935150,0.825100,0.919278,0.079301,-0.013549,0.007953,-0.156903,0.288315,NaN,NaN,0.932911,1.000000,0.416212,-0.080313,0.098217,-0.267777
remaining_area,0.703618,0.263048,0.204014,-0.173097,-0.107154,-0.159461,0.042948,0.358637,NaN,NaN,0.440977,0.416212,1.000000,-0.123813,-0.140544,-0.085032
convenience,-0.115208,-0.060816,-0.012023,0.300881,-0.046871,0.834418,0.405349,-0.135201,NaN,NaN,-0.107125,-0.080313,-0.123813,1.000000,0.096212,-0.058230
distance_from_central,0.016401,0.124686,0.197414,0.767263,0.361373,0.342337,-0.395673,-0.007425,NaN,NaN,0.050286,0.098217,-0.140544,0.096212,1.000000,-0.730136
price_sqft,-0.236302,-0.268653,-0.317825,-0.674457,-0.203385,-0.350656,0.477437,-0.308243,NaN,NaN,-0.229385,-0.267777,-0.085032,-0.058230,-0.730136,1.000000

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold

In [40]:
Y = condo['price_sqft']
Y

2408     919.32
2409    2699.78
2410    1871.26
2411    1438.98
2412    1917.81
         ...
5941     965.82
5942    1292.93
5943     929.25
5944     791.79
5945    1019.74
Name: price_sqft, Length: 3538, dtype: float64

In [64]:
for i in [2,3,4]:
    data = df
    poly = PolynomialFeatures(degree=i)
    X = poly.fit_transform(data.iloc[:,:-1])
    Y = data['price_sqft']
    kfold = KFold(n_splits=5)
    
    diff_max = []
    diff_min = []
    pred_max = []
    pred_min = []
    err = []

    for train_idx, test_idx in kfold.split(Y):
        train_x = X[train_idx]
        train_y = Y[train_idx]
        test_x = X[test_idx]
        test_y = Y[test_idx]

        linreg = LinearRegression()
        linreg.fit(train_x, train_y)
        y_pred = linreg.predict(test_x)
        err.append(np.sqrt(mean_squared_error(y_pred, test_y)))
        pred_max.append(np.max(y_pred))
        pred_min.append(np.min(y_pred))
        diff_max.append(np.max(y_pred - test_y))
        diff_min.append(np.min(y_pred - test_y))
        print('Done')

    
    print()
    print("Pred max: ", np.max(pred_max))
    print("Pred min: ", np.min(pred_min))
    print("Diff max: ", np.max(diff_max))
    print("Diff min: ", np.min(diff_min))
    print()
    print(err)
    print(np.mean(err))
    print()

Done
Done
Done
Done
Done

Pred max:  2532.908786110347
Pred min:  -1756.0226984303445
Diff max:  1239.3199846751243
Diff min:  -3150.2526984303445

[102.6266814026886, 86.03470827958427, 229.5962934430952, 249.83485772443973, 237.4002229939422]
181.09855276875

Done
Done
Done
Done
Done

Pred max:  76982.76434991136
Pred min:  -331.94013430178165
Diff max:  75588.53434991137
Diff min:  -2147.690278994888

[115.00204678611183, 106.21955264125621, 214.58743163053774, 2202.9336013057373, 223.06349535102407]
572.3612255429334

Done
Done
Done
Done
Done

Pred max:  1057585.0163030345
Pred min:  -9581003.253610866
Diff max:  1056190.7863030345
Diff min:  -9581492.053610867

[279037.1531196334, 7640.706689199235, 7200.005937098772, 30841.873054108484, 1608.3238841660104]
65265.612536841174

In [65]:
from sklearn.linear_model import Ridge

for i in [2,3,4]:
    data = df
    poly = PolynomialFeatures(degree=i)
    X = poly.fit_transform(data.iloc[:,:-1])
    Y = data['price_sqft']
    kfold = KFold(n_splits=5)
    
    diff_max = []
    diff_min = []
    pred_max = []
    pred_min = []
    err = []

    for train_idx, test_idx in kfold.split(Y):
        train_x = X[train_idx]
        train_y = Y[train_idx]
        test_x = X[test_idx]
        test_y = Y[test_idx]

        linreg = Ridge(alpha=10)
        linreg.fit(train_x, train_y)
        y_pred = linreg.predict(test_x)
        err.append(np.sqrt(mean_squared_error(y_pred, test_y)))
        pred_max.append(np.max(y_pred))
        pred_min.append(np.min(y_pred))
        diff_max.append(np.max(y_pred - test_y))
        diff_min.append(np.min(y_pred - test_y))
        print('Done')

    
    print()
    print("Pred max: ", np.max(pred_max))
    print("Pred min: ", np.min(pred_min))
    print("Diff max: ", np.max(diff_max))
    print("Diff min: ", np.min(diff_min))
    print()
    print(err)
    print(np.mean(err))
    print()

Done
Done
Done
Done
Done

Pred max:  2515.8000858930536
Pred min:  -570.0964270696495
Diff max:  1283.3280295425513
Diff min:  -1556.6070487445513

[94.96686081080922, 90.15994255880732, 233.36628644198052, 243.79360533527384, 240.49353307354625]
180.55604564408344

Done
Done
Done
Done
Done

Pred max:  20066.289983355848
Pred min:  -113.85620167168963
Diff max:  18672.059983355848
Diff min:  -2611.6490798732057

[128.34300549036385, 92.9626623141522, 225.1345303720082, 589.010510623993, 234.47813809561663]
253.9857693792268

Done
Done
Done
Done
Done

Pred max:  4511992.407329304
Pred min:  -188221.12718607712
Diff max:  4511503.607329304
Diff min:  -188671.96718607712

[130900.28733356, 1999.409829249836, 3575.7902183207734, 3444.6531443411227, 727.7035130485583]
28129.56880770406

In [78]:
linreg = Ridge(alpha=1)

poly = PolynomialFeatures(degree=2)
linreg.fit(poly.fit_transform(df.iloc[:,:-1]), df.iloc[:,-1])
# area 	bathroom 	bedroom 	lat 	long 	school 	mrt 	age 	type_condo 	type_hdb 	bathroom_area 	bedroom_area 	remaining_area 	convenience 	distance_from_central
x = poly.transform(np.array([[958, 2, 3, 1.321328, 103.866836, 1, 2, 10, 0, 1, 143.7, 359,456,3,4.28]]))
linreg.predict(x)

C:\Users\TNG\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=3.06174e-17): result may not be accurate.
  overwrite_a=True).T

array([785.69080867])

In [71]:
df

,area,bathroom,bedroom,lat,long,school,mrt,age,type_condo,type_hdb,bathroom_area,bedroom_area,remaining_area,convenience,distance_from_central,price_sqft
0,1270,2,3,1.345383,103.746047,3,0,25,0,1,127.00,476.250,666.750,3,10.582454,429.92
1,1270,2,3,1.373571,103.851553,2,1,40,0,1,127.00,476.250,666.750,3,8.002258,533.86
2,990,2,2,1.315350,103.770855,2,0,43,0,1,99.00,247.500,643.500,2,6.895952,459.60
3,1400,2,3,1.448271,103.813344,4,0,21,0,1,140.00,525.000,735.000,4,16.085163,371.43
4,905,2,3,1.372392,103.889038,6,1,35,0,1,90.50,339.375,475.125,7,9.889811,386.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5941,1346,3,4,1.389600,103.769447,3,0,6,1,0,201.90,673.000,471.100,3,11.736035,965.82
5942,495,1,1,1.395072,103.881105,5,0,3,1,0,24.75,61.875,408.375,5,11.469992,1292.93
5943,947,2,2,1.356282,103.968653,1,0,14,1,0,94.70,236.750,615.550,1,16.292776,929.25
5944,1023,2,2,1.352088,103.756707,3,0,21,1,0,102.30,255.750,664.950,3,9.904135,791.79
5945,1520,3,3,1.397350,103.896880,7,0,10,1,0,228.00,570.000,722.000,7,12.611621,1019.74